SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE acl_classes;
DROP TABLE acl_entries;
DROP TABLE acl_object_identities;
DROP TABLE acl_object_identity_ancestors;
DROP TABLE acl_security_identities;
DROP TABLE akeneo_batch_job_execution ;
DROP TABLE akeneo_batch_job_instance;
DROP TABLE akeneo_batch_mapping_field ;
DROP TABLE akeneo_batch_mapping_item;
DROP TABLE akeneo_batch_step_execution;
DROP TABLE akeneo_batch_warning ;
DROP TABLE oro_access_group ;
DROP TABLE oro_access_role;
DROP TABLE oro_activity_list;
DROP TABLE oro_activity_owner ;
DROP TABLE oro_address;
DROP TABLE oro_address_type ;
DROP TABLE oro_address_type_translation ;
DROP TABLE oro_api_async_data ;
DROP TABLE oro_api_async_operation;
DROP TABLE oro_attachment ;
DROP TABLE oro_attachment_file;
DROP TABLE oro_attachment_file_item ;
DROP TABLE oro_attribute_family ;
DROP TABLE oro_attribute_family_label ;
DROP TABLE oro_attribute_group;
DROP TABLE oro_attribute_group_label;
DROP TABLE oro_attribute_group_rel;
DROP TABLE oro_audit;
DROP TABLE oro_audit_field;
DROP TABLE oro_brand;
DROP TABLE oro_brand_description;
DROP TABLE oro_brand_name ;
DROP TABLE oro_brand_short_desc ;
DROP TABLE oro_brand_slug ;
DROP TABLE oro_brand_slug_prototype ;
DROP TABLE oro_business_unit;
DROP TABLE oro_calendar ;
DROP TABLE oro_calendar_date;
DROP TABLE oro_calendar_event ;
DROP TABLE oro_calendar_event_attendee;
DROP TABLE oro_calendar_property;
DROP TABLE oro_calendar_recurrence;
DROP TABLE oro_catalog_cat_l_descr;
DROP TABLE oro_catalog_cat_s_descr;
DROP TABLE oro_catalog_cat_slug ;
DROP TABLE oro_catalog_cat_slug_prototype ;
DROP TABLE oro_catalog_cat_title;
DROP TABLE oro_catalog_category ;
DROP TABLE oro_category_def_prod_opts ;
DROP TABLE oro_category_visibility;
DROP TABLE oro_checkout ;
DROP TABLE oro_checkout_line_item ;
DROP TABLE oro_checkout_source;
DROP TABLE oro_checkout_subtotal;
DROP TABLE oro_checkout_workflow_state;
DROP TABLE oro_cmb_pl_to_pl ;
DROP TABLE oro_cmb_plist_to_cus_gr;
DROP TABLE oro_cmb_price_list_to_cus;
DROP TABLE oro_cmb_price_list_to_ws ;
DROP TABLE oro_cms_content_block;
DROP TABLE oro_cms_content_block_scope;
DROP TABLE oro_cms_content_block_title;
DROP TABLE oro_cms_content_widget ;
DROP TABLE oro_cms_content_widget_usage ;
DROP TABLE oro_cms_image_slide;
DROP TABLE oro_cms_login_page ;
DROP TABLE oro_cms_page ;
DROP TABLE oro_cms_page_slug_prototype;
DROP TABLE oro_cms_page_title ;
DROP TABLE oro_cms_page_to_slug ;
DROP TABLE oro_cms_text_content_variant ;
DROP TABLE oro_cms_txt_cont_variant_scope ;
DROP TABLE oro_comment;
DROP TABLE oro_commerce_menu_upd;
DROP TABLE oro_commerce_menu_upd_descr;
DROP TABLE oro_commerce_menu_upd_title;
DROP TABLE oro_config ;
DROP TABLE oro_config_value ;
DROP TABLE oro_consent;
DROP TABLE oro_consent_acceptance ;
DROP TABLE oro_consent_name ;
DROP TABLE oro_cpl_activation_rule;
DROP TABLE oro_cron_schedule;
DROP TABLE oro_ctgr_vsb_resolv;
DROP TABLE oro_cus_category_visibility;
DROP TABLE oro_cus_ctgr_vsb_resolv;
DROP TABLE oro_cus_grp_ctgr_visibility;
DROP TABLE oro_cus_grp_ctgr_vsb_resolv;
DROP TABLE oro_cus_grp_prod_visibility;
DROP TABLE oro_cus_grp_prod_vsb_resolv;
DROP TABLE oro_cus_nav_item_pinbar;
DROP TABLE oro_cus_navigation_history ;
DROP TABLE oro_cus_navigation_item;
DROP TABLE oro_cus_pagestate;
DROP TABLE oro_cus_prod_vsb_resolv;
DROP TABLE oro_cus_product_visibility ;
DROP TABLE oro_cus_user_access_role ;
DROP TABLE oro_cus_usr_adr_to_adr_type;
DROP TABLE oro_cus_windows_state;
DROP TABLE oro_customer ;
DROP TABLE oro_customer_address ;
DROP TABLE oro_customer_adr_adr_type;
DROP TABLE oro_customer_group ;
DROP TABLE oro_customer_sales_reps;
DROP TABLE oro_customer_user;
DROP TABLE oro_customer_user_address;
DROP TABLE oro_customer_user_api;
DROP TABLE oro_customer_user_role ;
DROP TABLE oro_customer_user_sales_reps ;
DROP TABLE oro_customer_user_sdbar_st ;
DROP TABLE oro_customer_user_sdbar_wdg;
DROP TABLE oro_customer_user_settings ;
DROP TABLE oro_customer_visitor ;
DROP TABLE oro_dashboard;
DROP TABLE oro_dashboard_active ;
DROP TABLE oro_dashboard_widget ;
DROP TABLE oro_dashboard_widget_state ;
DROP TABLE oro_dictionary_country ;
DROP TABLE oro_dictionary_country_trans ;
DROP TABLE oro_dictionary_region;
DROP TABLE oro_dictionary_region_trans;
DROP TABLE oro_digital_asset;
DROP TABLE oro_digital_asset_title;
DROP TABLE oro_draft_project;
DROP TABLE oro_email;
DROP TABLE oro_email_address;
DROP TABLE oro_email_attachment ;
DROP TABLE oro_email_attachment_content ;
DROP TABLE oro_email_auto_response_rule ;
DROP TABLE oro_email_body ;
DROP TABLE oro_email_folder ;
DROP TABLE oro_email_folder_imap;
DROP TABLE oro_email_imap ;
DROP TABLE oro_email_mailbox;
DROP TABLE oro_email_mailbox_process;
DROP TABLE oro_email_mailbox_roles;
DROP TABLE oro_email_mailbox_users;
DROP TABLE oro_email_origin ;
DROP TABLE oro_email_recipient;
DROP TABLE oro_email_template ;
DROP TABLE oro_email_template_localized ;
DROP TABLE oro_email_thread ;
DROP TABLE oro_email_user ;
DROP TABLE oro_email_user_folders ;
DROP TABLE oro_embedded_form;
DROP TABLE oro_entity_config;
DROP TABLE oro_entity_config_field;
DROP TABLE oro_entity_config_index_value;
DROP TABLE oro_entity_config_log;
DROP TABLE oro_entity_config_log_diff ;
DROP TABLE oro_entity_fallback_value;
DROP TABLE oro_enum_acc_internal_rating ;
DROP TABLE oro_enum_auth_status ;
DROP TABLE oro_enum_ce_attendee_status;
DROP TABLE oro_enum_ce_attendee_type;
DROP TABLE oro_enum_dm_ab_cnt_exp_type;
DROP TABLE oro_enum_dm_ab_visibility;
DROP TABLE oro_enum_dm_cmp_reply_action ;
DROP TABLE oro_enum_dm_cmp_status ;
DROP TABLE oro_enum_dm_cnt_email_type ;
DROP TABLE oro_enum_dm_cnt_opt_in_type;
DROP TABLE oro_enum_dm_cnt_status ;
DROP TABLE oro_enum_dm_df_type;
DROP TABLE oro_enum_dm_df_visibility;
DROP TABLE oro_enum_dm_import_status;
DROP TABLE oro_enum_lead_source ;
DROP TABLE oro_enum_lead_status ;
DROP TABLE oro_enum_ma_type ;
DROP TABLE oro_enum_opportunity_status;
DROP TABLE oro_enum_order_internal_status ;
DROP TABLE oro_enum_prod_inventory_status ;
DROP TABLE oro_enum_quote_customer_status ;
DROP TABLE oro_enum_quote_internal_status ;
DROP TABLE oro_enum_rfp_customer_status ;
DROP TABLE oro_enum_rfp_internal_status ;
DROP TABLE oro_enum_task_status ;
DROP TABLE oro_enum_value_trans ;
DROP TABLE oro_fallback_localization_val;
DROP TABLE oro_fedex_ship_service_rule;
DROP TABLE oro_fedex_shipping_service ;
DROP TABLE oro_fedex_transp_ship_service;
DROP TABLE oro_fedex_transport_label;
DROP TABLE oro_flat_rate_transport_label;
DROP TABLE oro_grid_appearance_type ;
DROP TABLE oro_grid_view;
DROP TABLE oro_grid_view_user_rel ;
DROP TABLE oro_imap_wrong_creds_origin;
DROP TABLE oro_import_export_result ;
DROP TABLE oro_integration_channel;
DROP TABLE oro_integration_channel_status ;
DROP TABLE oro_integration_fields_changes ;
DROP TABLE oro_integration_transport;
DROP TABLE oro_inventory_level;
DROP TABLE oro_language ;
DROP TABLE oro_localization ;
DROP TABLE oro_localization_title ;
DROP TABLE oro_logger_log_entry ;
DROP TABLE oro_menu_user_agent_condition;
DROP TABLE oro_message_queue;
DROP TABLE oro_message_queue_job;
DROP TABLE oro_message_queue_job_unique ;
DROP TABLE oro_message_queue_state;
DROP TABLE oro_migrations ;
DROP TABLE oro_migrations_data;
DROP TABLE oro_money_order_short_label;
DROP TABLE oro_money_order_trans_label;
DROP TABLE oro_navigation_history ;
DROP TABLE oro_navigation_item;
DROP TABLE oro_navigation_item_pinbar ;
DROP TABLE oro_navigation_menu_upd;
DROP TABLE oro_navigation_menu_upd_descr;
DROP TABLE oro_navigation_menu_upd_title;
DROP TABLE oro_navigation_pagestate ;
DROP TABLE oro_note ;
DROP TABLE oro_notification_email_notif ;
DROP TABLE oro_notification_email_spool ;
DROP TABLE oro_notification_mass_notif;
DROP TABLE oro_notification_message ;
DROP TABLE oro_notification_recip_group ;
DROP TABLE oro_notification_recip_list;
DROP TABLE oro_notification_recip_user;
DROP TABLE oro_oauth2_access_token;
DROP TABLE oro_oauth2_auth_code ;
DROP TABLE oro_oauth2_client;
DROP TABLE oro_oauth2_refresh_token ;
DROP TABLE oro_order;
DROP TABLE oro_order_address;
DROP TABLE oro_order_discount ;
DROP TABLE oro_order_line_item;
DROP TABLE oro_order_shipping_tracking;
DROP TABLE oro_organization ;
DROP TABLE oro_payment_method_config;
DROP TABLE oro_payment_mtds_cfgs_rl ;
DROP TABLE oro_payment_mtds_cfgs_rl_d ;
DROP TABLE oro_payment_mtds_rule_website;
DROP TABLE oro_payment_mtdscfgsrl_dst_pc;
DROP TABLE oro_payment_status ;
DROP TABLE oro_payment_term ;
DROP TABLE oro_payment_term_short_label ;
DROP TABLE oro_payment_term_trans_label ;
DROP TABLE oro_payment_transaction;
DROP TABLE oro_paypal_credit_card_lbl ;
DROP TABLE oro_paypal_credit_card_sh_lbl;
DROP TABLE oro_paypal_xprss_chkt_lbl;
DROP TABLE oro_paypal_xprss_chkt_shrt_lbl ;
DROP TABLE oro_plist_curr_combined;
DROP TABLE oro_price_attribute_pl ;
DROP TABLE oro_price_attribute_price;
DROP TABLE oro_price_list ;
DROP TABLE oro_price_list_combined;
DROP TABLE oro_price_list_currency;
DROP TABLE oro_price_list_cus_fb;
DROP TABLE oro_price_list_cus_gr_fb ;
DROP TABLE oro_price_list_schedule;
DROP TABLE oro_price_list_to_cus_group;
DROP TABLE oro_price_list_to_customer ;
DROP TABLE oro_price_list_to_product;
DROP TABLE oro_price_list_to_website;
DROP TABLE oro_price_list_website_fb;
DROP TABLE oro_price_product;
DROP TABLE oro_price_product_combined ;
DROP TABLE oro_price_rule ;
DROP TABLE oro_price_rule_lexeme;
DROP TABLE oro_process_definition ;
DROP TABLE oro_process_job;
DROP TABLE oro_process_trigger;
DROP TABLE oro_prod_vsb_resolv;
DROP TABLE oro_product;
DROP TABLE oro_product_attr_currency;
DROP TABLE oro_product_image;
DROP TABLE oro_product_image_type ;
DROP TABLE oro_product_prod_descr ;
DROP TABLE oro_product_prod_name;
DROP TABLE oro_product_prod_s_descr ;
DROP TABLE oro_product_related_products ;
DROP TABLE oro_product_slug ;
DROP TABLE oro_product_slug_prototype ;
DROP TABLE oro_product_unit ;
DROP TABLE oro_product_unit_precision ;
DROP TABLE oro_product_upsell_product ;
DROP TABLE oro_product_variant_link ;
DROP TABLE oro_product_visibility ;
DROP TABLE oro_promotion;
DROP TABLE oro_promotion_applied;
DROP TABLE oro_promotion_applied_coupon ;
DROP TABLE oro_promotion_applied_discount ;
DROP TABLE oro_promotion_coupon ;
DROP TABLE oro_promotion_coupon_usage ;
DROP TABLE oro_promotion_description;
DROP TABLE oro_promotion_discount_config;
DROP TABLE oro_promotion_label;
DROP TABLE oro_promotion_schedule ;
DROP TABLE oro_promotion_scope;
DROP TABLE oro_quote_address;
DROP TABLE oro_quote_assigned_cus_users ;
DROP TABLE oro_quote_assigned_users ;
DROP TABLE oro_quote_demand ;
DROP TABLE oro_quote_product_demand ;
DROP TABLE oro_redirect ;
DROP TABLE oro_redirect_scope ;
DROP TABLE oro_redirect_slug;
DROP TABLE oro_rel_1cf73d3121a159ae2725f3 ;
DROP TABLE oro_rel_1cf73d3121a159ae6e1a29 ;
DROP TABLE oro_rel_1cf73d3121a159aea3971e ;
DROP TABLE oro_rel_265353702da17977bb66fd ;
DROP TABLE oro_rel_2653537034e8bc9c2ddbe0 ;
DROP TABLE oro_rel_265353703708e583c5ba51 ;
DROP TABLE oro_rel_2653537050ef1ed9f45d78 ;
DROP TABLE oro_rel_265353705154c0033bfb48 ;
DROP TABLE oro_rel_2653537083dfdfa436b4e2 ;
DROP TABLE oro_rel_2653537088a3cef53c57d4 ;
DROP TABLE oro_rel_265353709e0854fe254c12 ;
DROP TABLE oro_rel_26535370aab0e4f0b5ec88 ;
DROP TABLE oro_rel_26535370b28b6f3865ba50 ;
DROP TABLE oro_rel_26535370e65dd9d390636c ;
DROP TABLE oro_rel_26535370f24c741be77458 ;
DROP TABLE oro_rel_26535370f42ab603ec4b1d ;
DROP TABLE oro_rel_46a29d1934e8bc9c2ddbe0 ;
DROP TABLE oro_rel_46a29d193708e583c5ba51 ;
DROP TABLE oro_rel_46a29d195154c0033bfb48 ;
DROP TABLE oro_rel_46a29d1983dfdfa436b4e2 ;
DROP TABLE oro_rel_46a29d1988a3cef53c57d4 ;
DROP TABLE oro_rel_46a29d199e0854fe254c12 ;
DROP TABLE oro_rel_46a29d19aab0e4f0b5ec88 ;
DROP TABLE oro_rel_46a29d19b28b6f3865ba50 ;
DROP TABLE oro_rel_46a29d19e65dd9d390636c ;
DROP TABLE oro_rel_46a29d19f42ab603ec4b1d ;
DROP TABLE oro_rel_5b5187a321a159ae2725f3 ;
DROP TABLE oro_rel_5b5187a321a159ae6e1a29 ;
DROP TABLE oro_rel_5b5187a321a159aea3971e ;
DROP TABLE oro_rel_6cbc80002da17977bb66fd ;
DROP TABLE oro_rel_6cbc800050ef1ed9f45d78 ;
DROP TABLE oro_rel_6cbc80005154c0033bfb48 ;
DROP TABLE oro_rel_6cbc800083dfdfa436b4e2 ;
DROP TABLE oro_rel_6cbc800088a3cef53c57d4 ;
DROP TABLE oro_rel_6cbc80009e0854fe254c12 ;
DROP TABLE oro_rel_6cbc8000b28b6f3865ba50 ;
DROP TABLE oro_rel_6cbc8000e65dd9d390636c ;
DROP TABLE oro_rel_6f8f552a16cbf45882508f ;
DROP TABLE oro_rel_6f8f552a1cf73d3129e5bb ;
DROP TABLE oro_rel_6f8f552a2c175de41f8af0 ;
DROP TABLE oro_rel_6f8f552a34e8bc9c2ddbe0 ;
DROP TABLE oro_rel_6f8f552a3708e583c5ba51 ;
DROP TABLE oro_rel_6f8f552a43ecff72f0d342 ;
DROP TABLE oro_rel_6f8f552a5154c0033bfb48 ;
DROP TABLE oro_rel_6f8f552a5b5187a347fdf8 ;
DROP TABLE oro_rel_6f8f552a758542cfbd3dfc ;
DROP TABLE oro_rel_6f8f552a784fec5f9c970f ;
DROP TABLE oro_rel_6f8f552a7e0cc7f027a8f9 ;
DROP TABLE oro_rel_6f8f552a83dfdfa436b4e2 ;
DROP TABLE oro_rel_6f8f552a88a3cef53c57d4 ;
DROP TABLE oro_rel_6f8f552a88d2647be4fd56 ;
DROP TABLE oro_rel_6f8f552a9e0854fe254c12 ;
DROP TABLE oro_rel_6f8f552aa73c785c4e6d3f ;
DROP TABLE oro_rel_6f8f552aaab0e4f0b5ec88 ;
DROP TABLE oro_rel_6f8f552ab28b6f3865ba50 ;
DROP TABLE oro_rel_6f8f552ad7fa01cde46c56 ;
DROP TABLE oro_rel_6f8f552af42ab603ec4b1d ;
DROP TABLE oro_rel_6f8f552af9a91faa3967ca ;
DROP TABLE oro_rel_6f8f552aff3a7b97ec3308 ;
DROP TABLE oro_rel_b438191e21a159ae2725f3 ;
DROP TABLE oro_rel_b438191e21a159ae6e1a29 ;
DROP TABLE oro_rel_b438191e21a159aea3971e ;
DROP TABLE oro_rel_c3990ba616cbf45899499b ;
DROP TABLE oro_rel_c3990ba61cf73d31624686 ;
DROP TABLE oro_rel_c3990ba62653537081b7e1 ;
DROP TABLE oro_rel_c3990ba62c175de4fa9927 ;
DROP TABLE oro_rel_c3990ba62da17977270bd6 ;
DROP TABLE oro_rel_c3990ba634e8bc9cac53cb ;
DROP TABLE oro_rel_c3990ba63708e583a2c61e ;
DROP TABLE oro_rel_c3990ba643ecff72e2f6de ;
DROP TABLE oro_rel_c3990ba650ef1ed91c32d0 ;
DROP TABLE oro_rel_c3990ba65154c0069aa16e ;
DROP TABLE oro_rel_c3990ba65b5187a374e72c ;
DROP TABLE oro_rel_c3990ba6758542cf1cec5e ;
DROP TABLE oro_rel_c3990ba6784fec5f6e321b ;
DROP TABLE oro_rel_c3990ba67e0cc7f01d1498 ;
DROP TABLE oro_rel_c3990ba683dfdfa4a13cb3 ;
DROP TABLE oro_rel_c3990ba688a3cef5c8efa6 ;
DROP TABLE oro_rel_c3990ba688d2647b59a3ef ;
DROP TABLE oro_rel_c3990ba69e0854fe1d2e0c ;
DROP TABLE oro_rel_c3990ba6a73c785ca4a8ba ;
DROP TABLE oro_rel_c3990ba6aab0e4f07348a4 ;
DROP TABLE oro_rel_c3990ba6b28b6f38e2d624 ;
DROP TABLE oro_rel_c3990ba6d7fa01cd30d950 ;
DROP TABLE oro_rel_c3990ba6e65dd9d37deb67 ;
DROP TABLE oro_rel_c3990ba6f24c741b1d920a ;
DROP TABLE oro_rel_c3990ba6f42ab603ed4e03 ;
DROP TABLE oro_rel_c3990ba6f9a91faa5f648d ;
DROP TABLE oro_rel_c3990ba6ff3a7b97760f68 ;
DROP TABLE oro_rel_c56bdd4f6444702dedcb9c ;
DROP TABLE oro_rel_dd93d65c21a159ae2725f3 ;
DROP TABLE oro_rel_dd93d65c21a159ae6e1a29 ;
DROP TABLE oro_rel_dd93d65c21a159aea3971e ;
DROP TABLE oro_rel_f24c741b265353702dde5c ;
DROP TABLE oro_rel_f24c741b5154c0033bfb48 ;
DROP TABLE oro_rel_f24c741b83dfdfa436b4e2 ;
DROP TABLE oro_rel_f24c741b88a3cef53c57d4 ;
DROP TABLE oro_rel_f24c741b9e0854fe254c12 ;
DROP TABLE oro_rel_f24c741bb28b6f3865ba50 ;
DROP TABLE oro_rel_f24c741be65dd9d390636c ;
DROP TABLE oro_rel_ff3a7b9721a159ae2725f3 ;
DROP TABLE oro_rel_ff3a7b9721a159ae6e1a29 ;
DROP TABLE oro_rel_ff3a7b9721a159aea3971e ;
DROP TABLE oro_related_website;
DROP TABLE oro_reminder ;
DROP TABLE oro_report ;
DROP TABLE oro_report_type;
DROP TABLE oro_rfp_assigned_cus_users ;
DROP TABLE oro_rfp_assigned_users ;
DROP TABLE oro_rfp_request;
DROP TABLE oro_rfp_request_add_note ;
DROP TABLE oro_rfp_request_prod_item;
DROP TABLE oro_rfp_request_product;
DROP TABLE oro_rule ;
DROP TABLE oro_sale_quote ;
DROP TABLE oro_sale_quote_prod_offer;
DROP TABLE oro_sale_quote_prod_request;
DROP TABLE oro_sale_quote_product ;
DROP TABLE oro_scope;
DROP TABLE oro_search_index_datetime;
DROP TABLE oro_search_index_decimal ;
DROP TABLE oro_search_index_integer ;
DROP TABLE oro_search_index_text;
DROP TABLE oro_search_item;
DROP TABLE oro_search_query ;
DROP TABLE oro_security_perm_apply_entity ;
DROP TABLE oro_security_perm_excl_entity;
DROP TABLE oro_security_permission;
DROP TABLE oro_security_permission_entity ;
DROP TABLE oro_segment;
DROP TABLE oro_segment_snapshot ;
DROP TABLE oro_segment_type ;
DROP TABLE oro_session;
DROP TABLE oro_ship_method_config ;
DROP TABLE oro_ship_method_configs_rule ;
DROP TABLE oro_ship_method_postal_code;
DROP TABLE oro_ship_method_type_config;
DROP TABLE oro_ship_mtds_rule_website ;
DROP TABLE oro_shipping_freight_class ;
DROP TABLE oro_shipping_length_unit ;
DROP TABLE oro_shipping_product_opts;
DROP TABLE oro_shipping_rule_destination;
DROP TABLE oro_shipping_weight_unit ;
DROP TABLE oro_shopping_list;
DROP TABLE oro_shopping_list_line_item;
DROP TABLE oro_shopping_list_total;
DROP TABLE oro_sidebar_state;
DROP TABLE oro_sidebar_widget ;
DROP TABLE oro_slug_scope ;
DROP TABLE oro_system_calendar;
DROP TABLE oro_tag_tag;
DROP TABLE oro_tag_tagging;
DROP TABLE oro_tag_taxonomy ;
DROP TABLE oro_tax;
DROP TABLE oro_tax_customer_tax_code;
DROP TABLE oro_tax_jurisdiction ;
DROP TABLE oro_tax_prod_tax_code_prod ;
DROP TABLE oro_tax_product_tax_code ;
DROP TABLE oro_tax_rule ;
DROP TABLE oro_tax_value;
DROP TABLE oro_tax_zip_code ;
DROP TABLE oro_tracking_data;
DROP TABLE oro_tracking_event ;
DROP TABLE oro_tracking_event_dictionary;
DROP TABLE oro_tracking_unique_visit;
DROP TABLE oro_tracking_visit ;
DROP TABLE oro_tracking_visit_event ;
DROP TABLE oro_tracking_website ;
DROP TABLE oro_translation;
DROP TABLE oro_translation_key;
DROP TABLE oro_ups_shipping_service ;
DROP TABLE oro_ups_transport_label;
DROP TABLE oro_ups_transport_ship_service ;
DROP TABLE oro_user ;
DROP TABLE oro_user_access_group;
DROP TABLE oro_user_access_group_role ;
DROP TABLE oro_user_access_role ;
DROP TABLE oro_user_api ;
DROP TABLE oro_user_business_unit ;
DROP TABLE oro_user_email ;
DROP TABLE oro_user_impersonation ;
DROP TABLE oro_user_organization;
DROP TABLE oro_user_status;
DROP TABLE oro_web_catalog;
DROP TABLE oro_web_catalog_content_node ;
DROP TABLE oro_web_catalog_node_scope ;
DROP TABLE oro_web_catalog_node_slug_prot ;
DROP TABLE oro_web_catalog_node_title ;
DROP TABLE oro_web_catalog_node_url ;
DROP TABLE oro_web_catalog_product_limit;
DROP TABLE oro_web_catalog_variant;
DROP TABLE oro_web_catalog_variant_scope;
DROP TABLE oro_web_catalog_variant_slug ;
DROP TABLE oro_website;
DROP TABLE oro_website_search_datetime;
DROP TABLE oro_website_search_decimal ;
DROP TABLE oro_website_search_integer ;
DROP TABLE oro_website_search_item;
DROP TABLE oro_website_search_text;
DROP TABLE oro_windows_state;
DROP TABLE oro_workflow_definition;
DROP TABLE oro_workflow_entity_acl;
DROP TABLE oro_workflow_entity_acl_ident;
DROP TABLE oro_workflow_item;
DROP TABLE oro_workflow_restriction ;
DROP TABLE oro_workflow_restriction_ident ;
DROP TABLE oro_workflow_scopes;
DROP TABLE oro_workflow_step;
DROP TABLE oro_workflow_trans_trigger ;
DROP TABLE oro_workflow_transition_log;
DROP TABLE orocrm_account ;
DROP TABLE orocrm_account_to_contact;
DROP TABLE orocrm_analytics_rfm_category;
DROP TABLE orocrm_call;
DROP TABLE orocrm_call_direction;
DROP TABLE orocrm_call_direction_trans;
DROP TABLE orocrm_call_status ;
DROP TABLE orocrm_call_status_trans ;
DROP TABLE orocrm_campaign;
DROP TABLE orocrm_campaign_code_history ;
DROP TABLE orocrm_campaign_email;
DROP TABLE orocrm_campaign_email_stats;
DROP TABLE orocrm_campaign_te_summary ;
DROP TABLE orocrm_case;
DROP TABLE orocrm_case_comment;
DROP TABLE orocrm_case_priority ;
DROP TABLE orocrm_case_priority_trans ;
DROP TABLE orocrm_case_source ;
DROP TABLE orocrm_case_source_trans ;
DROP TABLE orocrm_case_status ;
DROP TABLE orocrm_case_status_trans ;
DROP TABLE orocrm_channel ;
DROP TABLE orocrm_channel_cust_identity ;
DROP TABLE orocrm_channel_entity_name ;
DROP TABLE orocrm_channel_lifetime_hist ;
DROP TABLE orocrm_channel_ltime_avg_aggr;
DROP TABLE orocrm_cmpgn_transport_stngs ;
DROP TABLE orocrm_contact ;
DROP TABLE orocrm_contact_address ;
DROP TABLE orocrm_contact_adr_to_adr_type ;
DROP TABLE orocrm_contact_email ;
DROP TABLE orocrm_contact_group ;
DROP TABLE orocrm_contact_method;
DROP TABLE orocrm_contact_phone ;
DROP TABLE orocrm_contact_source;
DROP TABLE orocrm_contact_to_contact_grp;
DROP TABLE orocrm_contactus_contact_rsn ;
DROP TABLE orocrm_contactus_contact_rsn_t ;
DROP TABLE orocrm_contactus_req_emails;
DROP TABLE orocrm_contactus_request ;
DROP TABLE orocrm_dm_ab_cnt_export;
DROP TABLE orocrm_dm_ab_contact ;
DROP TABLE orocrm_dm_activity ;
DROP TABLE orocrm_dm_address_book ;
DROP TABLE orocrm_dm_campaign ;
DROP TABLE orocrm_dm_campaign_summary ;
DROP TABLE orocrm_dm_campaign_to_ab ;
DROP TABLE orocrm_dm_change_field_log ;
DROP TABLE orocrm_dm_contact;
DROP TABLE orocrm_dm_data_field ;
DROP TABLE orocrm_dm_df_mapping ;
DROP TABLE orocrm_dm_df_mapping_config;
DROP TABLE orocrm_dm_oauth;
DROP TABLE orocrm_marketing_activity;
DROP TABLE orocrm_marketing_list;
DROP TABLE orocrm_marketing_list_item ;
DROP TABLE orocrm_marketing_list_type ;
DROP TABLE orocrm_ml_item_rm;
DROP TABLE orocrm_ml_item_uns ;
DROP TABLE orocrm_sales_b2bcustomer ;
DROP TABLE orocrm_sales_b2bcustomer_email ;
DROP TABLE orocrm_sales_b2bcustomer_phone ;
DROP TABLE orocrm_sales_customer;
DROP TABLE orocrm_sales_funnel;
DROP TABLE orocrm_sales_lead;
DROP TABLE orocrm_sales_lead_address;
DROP TABLE orocrm_sales_lead_email;
DROP TABLE orocrm_sales_lead_phone;
DROP TABLE orocrm_sales_opport_close_rsn;
DROP TABLE orocrm_sales_opportunity ;
DROP TABLE orocrm_task;
DROP TABLE orocrm_task_priority ;
DROP TABLE orocrm_zd_comment;
DROP TABLE orocrm_zd_ticket ;
DROP TABLE orocrm_zd_ticket_collaborators ;
DROP TABLE orocrm_zd_ticket_priority;
DROP TABLE orocrm_zd_ticket_priority_tran ;
DROP TABLE orocrm_zd_ticket_status;
DROP TABLE orocrm_zd_ticket_status_trans;
DROP TABLE orocrm_zd_ticket_type;
DROP TABLE orocrm_zd_ticket_type_trans;
DROP TABLE orocrm_zd_user ;
DROP TABLE orocrm_zd_user_role;
DROP TABLE orocrm_zd_user_role_trans;
DROP TABLE rememberme_token ;